spring:
  application:
    name: RestAPIs


  datasource:
    url: jdbc:mysql://localhost:3306/spring_rest
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql : true



server:
  servlet:
    context-path: /api
